language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -U pip
  - python ./setup.py develop
before_script:
  - pip install -r requirements-test.txt
script:
  - pytest test/test_wheres.py
after_success:
  - coveralls
